### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by gianpaj** [gianpaj/swipefollowers#1]
- [ ] Welcome screen showing how to use the app
- [x] Twitter login with OAuth (~~native~~ if possible)
- [ ] Sort by last time the person tweeted
- [ ] Undo functionality (3 secs)
- [ ] Reset button to add those again
- [ ] Swipe up and down to learn more about Twitter account
- [ ] Show last tweet, RT, pic, etc.
- [ ] Lock orientation
- [ ] Write one unit test (I can do it!)
- [ ] Write one integration test
